# Generated by Django 4.0.6 on 2022-08-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0010_alter_gallery_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Индекс')),
                ('status', models.CharField(choices=[('PCG', 'формирование'), ('ABL', 'сборка заказа'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('CNL', 'отменен')], default='PCG', max_length=3, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='orderapp.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Структура заказа',
                'verbose_name_plural': 'Структура заказа',
                'db_table': 'orderitem',
            },
        ),
    ]
