# Generated by Django 4.0.6 on 2022-08-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PCG', 'формирование'), ('ABL', 'сборка заказа'), ('PD', 'оплачен'), ('RDY', 'готов к выдаче'), ('CNL', 'отменен')], default='PD', max_length=3, verbose_name='статус'),
        ),
    ]
