# Generated by Django 4.0.6 on 2022-08-06 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Город'),
        ),
    ]
