# Generated by Django 4.0.6 on 2022-08-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_alter_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress',
            new_name='address',
        ),
    ]
