# Generated by Django 4.0.6 on 2022-07-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='categories',
        ),
    ]
