# Generated by Django 4.0.6 on 2022-07-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0006_alter_genders_options_remove_genders_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.DeleteModel(
            name='Genders',
        ),
    ]
