# Generated by Django 4.0.6 on 2022-08-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0014_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
