# Generated by Django 4.0.6 on 2022-08-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0015_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=True, upload_to='category_images'),
        ),
    ]
